artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  URL: https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing
  local_data_path: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/model.h5
  update_model_path: artifacts/prepare_base_model/update_model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5  
  update_model_path: artifacts/prepare_base_model/update_model.h5

